language: crystal
crystal:
  - latest
  - nightly
install:
  - shards install
matrix:
  allow_failures:
    - crystal: nightly
script:
    - npm install
    - npm start &
    - crystal spec
    - shards build
    - bin/ameba
