language: crystal
crystal:
  - latest
  - nightly
install:
  - shards install
matrix:
  allow_failures:
    - crystal: nightly
script:
    - crystal tool format --check
    - bin/ameba
    - crystal spec
